name: MergeToMain
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  deploy_dev:
    name: DeployToDev
    uses: ./.github/workflows/deploy_adf.yml
    with:
      resource_group: 'gd-test-asa-rg'
      data_factory: 'gd-test-df'
      target_data_factory: 'gd-test-df'
      pause_triggers: false
      overwrite_references: false
    secrets:
      client_id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
